_bulk_docs:
    pattern: /{dbname}/_bulk_docs
    defaults: { _controller: WalterraCouchphpdbBundle:Document:bulkDocs, _format: json }
    requirements:
        _method: POST

_all_docs:
    pattern: /{dbname}/_all_docs
    defaults: { _controller: WalterraCouchphpdbBundle:Document:allDocs, _format: json }
    requirements:
        _method: GET

_doc:
    pattern: /{dbname}/{docname}
    defaults: { _controller: WalterraCouchphpdbBundle:Document:doc, _format: json }
    requirements:
        docname: "[a-zA-Z0-9-_/:\.]+"
    
_design_doc:
    pattern: /{dbname}/_design/{designdocname}
    defaults: { _controller: WalterraCouchphpdbBundle:Document:designDoc, _format: json }
    
_design_view:
    pattern: /{dbname}/_design/{designdocname}/_view/{viewname}
    defaults: { _controller: WalterraCouchphpdbBundle:View:view, _format: json }
    
_config_query_servers:
    pattern: /_config/query_servers/ 
    defaults: { _controller: WalterraCouchphpdbBundle:Config:queryServers, _format: json }
    requirements:
        _method: GET

_config_native_query_servers:
    pattern: _config/native_query_servers/
    defaults: { _controller: WalterraCouchphpdbBundle:Config:nativeQueryServers, _format: json }
    requirements:
        _method: GET

_session:
    pattern: _session
    defaults: { _controller: WalterraCouchphpdbBundle:Session:login, _format: json }
    requirements:
        _method: GET

_all_dbs:
    pattern: /_all_dbs
    defaults: { _controller: WalterraCouchphpdbBundle:Database:allDb, _format: json }
    requirements:
        _method: GET

_uuids:
    pattern: /_uuids{trailingSlash}
    defaults: { _controller: WalterraCouchphpdbBundle:Database:uuids, _format: json, trailingSlash : "/" }
    requirements: { _method: GET, trailingSlash : "[/]{0,1}" }

_db_name:
    pattern: /{dbname}{trailingSlash}
    defaults: { _controller: WalterraCouchphpdbBundle:Database:db, _format: json, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }

_welcome:
    pattern: /
    defaults: { _controller: WalterraCouchphpdbBundle:Welcome:index, _format: json }
    requirements:
        _method: GET

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
